/**
 * Mapa concelho → distrito (Portugal continental). Datos de referencia estables
 * derivados de la Carta Administrativa Oficial de Portugal (CAOP/INE): NO cambian
 * con el dato en vivo. Sirven para asignar la «provincia» (distrito) a los
 * incendios de la ANEPC, cuyo feed publica concelho/região/sub-região pero NO
 * distrito (a diferencia de fogos.pt, que sí trae `district`).
 *
 * Las claves están normalizadas (minúsculas, sin acentos) para casar con la
 * grafía de la fuente sin depender de mayúsculas/tildes. Los valores usan la
 * grafía canónica de `src/lib/geo/provinces.ts` (PT_DISTRICTS). Açores y Madeira
 * quedan fuera (son regiones autónomas sin distrito y están fuera del ámbito
 * satelital de Incendib).
 */

const CONCELHO_DISTRICT: Record<string, string> = {
  'abrantes': 'Santarém',
  'agueda': 'Aveiro',
  'aguiar da beira': 'Guarda',
  'alandroal': 'Évora',
  'albergaria-a-velha': 'Aveiro',
  'albufeira': 'Faro',
  'alcacer do sal': 'Setúbal',
  'alcanena': 'Santarém',
  'alcobaca': 'Leiria',
  'alcochete': 'Setúbal',
  'alcoutim': 'Faro',
  'alenquer': 'Lisboa',
  'alfandega da fe': 'Bragança',
  'alijo': 'Vila Real',
  'aljezur': 'Faro',
  'aljustrel': 'Beja',
  'almada': 'Setúbal',
  'almeida': 'Guarda',
  'almeirim': 'Santarém',
  'almodovar': 'Beja',
  'alpiarca': 'Santarém',
  'alter do chao': 'Portalegre',
  'alvaiazere': 'Leiria',
  'alvito': 'Beja',
  'amadora': 'Lisboa',
  'amarante': 'Porto',
  'amares': 'Braga',
  'anadia': 'Aveiro',
  'ansiao': 'Leiria',
  'arcos de valdevez': 'Viana do Castelo',
  'arganil': 'Coimbra',
  'armamar': 'Viseu',
  'arouca': 'Aveiro',
  'arraiolos': 'Évora',
  'arronches': 'Portalegre',
  'arruda dos vinhos': 'Lisboa',
  'aveiro': 'Aveiro',
  'avis': 'Portalegre',
  'azambuja': 'Lisboa',
  'baiao': 'Porto',
  'barcelos': 'Braga',
  'barrancos': 'Beja',
  'barreiro': 'Setúbal',
  'batalha': 'Leiria',
  'beja': 'Beja',
  'belmonte': 'Castelo Branco',
  'benavente': 'Santarém',
  'bombarral': 'Leiria',
  'borba': 'Évora',
  'boticas': 'Vila Real',
  'braga': 'Braga',
  'braganca': 'Bragança',
  'cabeceiras de basto': 'Braga',
  'cadaval': 'Lisboa',
  'caldas da rainha': 'Leiria',
  'caminha': 'Viana do Castelo',
  'campo maior': 'Portalegre',
  'cantanhede': 'Coimbra',
  'carrazeda de ansiaes': 'Bragança',
  'carregal do sal': 'Viseu',
  'cartaxo': 'Santarém',
  'cascais': 'Lisboa',
  'castanheira de pera': 'Leiria',
  'castelo branco': 'Castelo Branco',
  'castelo de paiva': 'Aveiro',
  'castelo de vide': 'Portalegre',
  'castro daire': 'Viseu',
  'castro marim': 'Faro',
  'castro verde': 'Beja',
  'celorico da beira': 'Guarda',
  'celorico de basto': 'Braga',
  'chamusca': 'Santarém',
  'chaves': 'Vila Real',
  'cinfaes': 'Viseu',
  'coimbra': 'Coimbra',
  'condeixa-a-nova': 'Coimbra',
  'constancia': 'Santarém',
  'coruche': 'Santarém',
  'covilha': 'Castelo Branco',
  'crato': 'Portalegre',
  'cuba': 'Beja',
  'elvas': 'Portalegre',
  'entroncamento': 'Santarém',
  'espinho': 'Aveiro',
  'esposende': 'Braga',
  'estarreja': 'Aveiro',
  'estremoz': 'Évora',
  'evora': 'Évora',
  'fafe': 'Braga',
  'faro': 'Faro',
  'felgueiras': 'Porto',
  'ferreira do alentejo': 'Beja',
  'ferreira do zezere': 'Santarém',
  'figueira da foz': 'Coimbra',
  'figueira de castelo rodrigo': 'Guarda',
  'figueiro dos vinhos': 'Leiria',
  'fornos de algodres': 'Guarda',
  'freixo de espada a cinta': 'Bragança',
  'fronteira': 'Portalegre',
  'fundao': 'Castelo Branco',
  'gaviao': 'Portalegre',
  'gois': 'Coimbra',
  'golega': 'Santarém',
  'gondomar': 'Porto',
  'gouveia': 'Guarda',
  'grandola': 'Setúbal',
  'guarda': 'Guarda',
  'guimaraes': 'Braga',
  'idanha-a-nova': 'Castelo Branco',
  'ilhavo': 'Aveiro',
  'lagoa': 'Faro',
  'lagos': 'Faro',
  'lamego': 'Viseu',
  'leiria': 'Leiria',
  'lisboa': 'Lisboa',
  'loule': 'Faro',
  'loures': 'Lisboa',
  'lourinha': 'Lisboa',
  'lousa': 'Coimbra',
  'lousada': 'Porto',
  'macao': 'Santarém',
  'macedo de cavaleiros': 'Bragança',
  'mafra': 'Lisboa',
  'maia': 'Porto',
  'mangualde': 'Viseu',
  'manteigas': 'Guarda',
  'marco de canaveses': 'Porto',
  'marinha grande': 'Leiria',
  'marvao': 'Portalegre',
  'matosinhos': 'Porto',
  'mealhada': 'Aveiro',
  'meda': 'Guarda',
  'melgaco': 'Viana do Castelo',
  'mertola': 'Beja',
  'mesao frio': 'Vila Real',
  'mira': 'Coimbra',
  'miranda do corvo': 'Coimbra',
  'miranda do douro': 'Bragança',
  'mirandela': 'Bragança',
  'mogadouro': 'Bragança',
  'moimenta da beira': 'Viseu',
  'moita': 'Setúbal',
  'moncao': 'Viana do Castelo',
  'monchique': 'Faro',
  'mondim de basto': 'Vila Real',
  'monforte': 'Portalegre',
  'montalegre': 'Vila Real',
  'montemor-o-novo': 'Évora',
  'montemor-o-velho': 'Coimbra',
  'montijo': 'Setúbal',
  'mora': 'Évora',
  'mortagua': 'Viseu',
  'moura': 'Beja',
  'mourao': 'Évora',
  'murca': 'Vila Real',
  'murtosa': 'Aveiro',
  'nazare': 'Leiria',
  'nelas': 'Viseu',
  'nisa': 'Portalegre',
  'obidos': 'Leiria',
  'odemira': 'Beja',
  'odivelas': 'Lisboa',
  'oeiras': 'Lisboa',
  'oleiros': 'Castelo Branco',
  'olhao': 'Faro',
  'oliveira de azemeis': 'Aveiro',
  'oliveira de frades': 'Viseu',
  'oliveira do bairro': 'Aveiro',
  'oliveira do hospital': 'Coimbra',
  'ourem': 'Santarém',
  'ourique': 'Beja',
  'ovar': 'Aveiro',
  'pacos de ferreira': 'Porto',
  'palmela': 'Setúbal',
  'pampilhosa da serra': 'Coimbra',
  'paredes': 'Porto',
  'paredes de coura': 'Viana do Castelo',
  'pedrogao grande': 'Leiria',
  'penacova': 'Coimbra',
  'penafiel': 'Porto',
  'penalva do castelo': 'Viseu',
  'penamacor': 'Castelo Branco',
  'penedono': 'Viseu',
  'penela': 'Coimbra',
  'peniche': 'Leiria',
  'peso da regua': 'Vila Real',
  'pinhel': 'Guarda',
  'pombal': 'Leiria',
  'ponte da barca': 'Viana do Castelo',
  'ponte de lima': 'Viana do Castelo',
  'ponte de sor': 'Portalegre',
  'portalegre': 'Portalegre',
  'portel': 'Évora',
  'portimao': 'Faro',
  'porto': 'Porto',
  'porto de mos': 'Leiria',
  'povoa de lanhoso': 'Braga',
  'povoa de varzim': 'Porto',
  'proenca-a-nova': 'Castelo Branco',
  'redondo': 'Évora',
  'reguengos de monsaraz': 'Évora',
  'resende': 'Viseu',
  'ribeira de pena': 'Vila Real',
  'rio maior': 'Santarém',
  'sabrosa': 'Vila Real',
  'sabugal': 'Guarda',
  'salvaterra de magos': 'Santarém',
  'santa comba dao': 'Viseu',
  'santa maria da feira': 'Aveiro',
  'santa marta de penaguiao': 'Vila Real',
  'santarem': 'Santarém',
  'santiago do cacem': 'Setúbal',
  'santo tirso': 'Porto',
  'sao bras de alportel': 'Faro',
  'sao joao da madeira': 'Aveiro',
  'sao joao da pesqueira': 'Viseu',
  'sao pedro do sul': 'Viseu',
  'sardoal': 'Santarém',
  'satao': 'Viseu',
  'seia': 'Guarda',
  'seixal': 'Setúbal',
  'sernancelhe': 'Viseu',
  'serpa': 'Beja',
  'serta': 'Castelo Branco',
  'sesimbra': 'Setúbal',
  'setubal': 'Setúbal',
  'sever do vouga': 'Aveiro',
  'silves': 'Faro',
  'sines': 'Setúbal',
  'sintra': 'Lisboa',
  'sobral de monte agraco': 'Lisboa',
  'soure': 'Coimbra',
  'sousel': 'Portalegre',
  'tabua': 'Coimbra',
  'tabuaco': 'Viseu',
  'tarouca': 'Viseu',
  'tavira': 'Faro',
  'terras de bouro': 'Braga',
  'tomar': 'Santarém',
  'tondela': 'Viseu',
  'torre de moncorvo': 'Bragança',
  'torres novas': 'Santarém',
  'torres vedras': 'Lisboa',
  'trancoso': 'Guarda',
  'trofa': 'Porto',
  'vagos': 'Aveiro',
  'vale de cambra': 'Aveiro',
  'valenca': 'Viana do Castelo',
  'valongo': 'Porto',
  'valpacos': 'Vila Real',
  'vendas novas': 'Évora',
  'viana do alentejo': 'Évora',
  'viana do castelo': 'Viana do Castelo',
  'vidigueira': 'Beja',
  'vieira do minho': 'Braga',
  'vila de rei': 'Castelo Branco',
  'vila do bispo': 'Faro',
  'vila do conde': 'Porto',
  'vila flor': 'Bragança',
  'vila franca de xira': 'Lisboa',
  'vila nova da barquinha': 'Santarém',
  'vila nova de cerveira': 'Viana do Castelo',
  'vila nova de famalicao': 'Braga',
  'vila nova de foz coa': 'Guarda',
  'vila nova de gaia': 'Porto',
  'vila nova de paiva': 'Viseu',
  'vila nova de poiares': 'Coimbra',
  'vila pouca de aguiar': 'Vila Real',
  'vila real': 'Vila Real',
  'vila real de santo antonio': 'Faro',
  'vila velha de rodao': 'Castelo Branco',
  'vila verde': 'Braga',
  'vila vicosa': 'Évora',
  'vimioso': 'Bragança',
  'vinhais': 'Bragança',
  'viseu': 'Viseu',
  'vizela': 'Braga',
  'vouzela': 'Viseu',
};

/** Normaliza un nombre para casar con las claves del mapa (sin acentos, minúsculas). */
function norm(s: string): string {
  return s
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .trim();
}

/**
 * Distrito (grafía canónica) de un concelho de Portugal continental, o null si no
 * está en el catálogo (p. ej. concelhos insulares o grafía no reconocida). El
 * llamante decide el respaldo (sub-região, região o «—»).
 */
export function districtForConcelho(concelho?: string | null): string | null {
  if (!concelho) return null;
  return CONCELHO_DISTRICT[norm(concelho)] ?? null;
}
